export const users = [
  {
    id: 0,
    name: "Chidinma Afolabi",
    status: "active",
    gender: "female",
    NHR_ID: "485 777 3456",
    age: 27,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
  {
    id: 1,
    name: "Chidinma Afolabi",
    status: "inactive",
    gender: "male",
    NHR_ID: "485 777 3456",
    age: 27,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
  {
    id: 2,
    name: "Chidinma Afolabi",
    status: "active",
    gender: "female",
    NHR_ID: "485 777 3456",
    age: 34,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
  {
    id: 3,
    name: "Chidinma Afolabi",
    status: "inactive",
    gender: "female",
    NHR_ID: "485 777 3456",
    age: 27,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
  {
    id: 4,
    name: "Chidinma Afolabi",
    status: "active",
    gender: "male",
    NHR_ID: "485 777 3456",
    age: 23,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
  {
    id: 5,
    name: "Chidinma Afolabi",
    status: "inactive",
    gender: "female",
    NHR_ID: "485 777 3456",
    age: 65,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
  {
    id: 6,
    name: "Chidinma Afolabi",
    status: "active",
    gender: "female",
    NHR_ID: "485 777 3456",
    age: 90,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
  {
    id: 7,
    name: "Chidinma Afolabi",
    status: "inactive",
    gender: "male",
    NHR_ID: "485 777 3456",
    age: 31,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
  {
    id: 8,
    name: "Chidinma Afolabi",
    status: "active",
    gender: "female",
    NHR_ID: "485 777 3456",
    age: 54,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
  {
    id: 9,
    name: "Chidinma Afolabi",
    status: "inactive",
    gender: "female",
    NHR_ID: "485 777 3456",
    age: 43,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
  {
    id: 10,
    name: "Chidinma Afolabi",
    status: "active",
    gender: "male",
    NHR_ID: "485 777 3456",
    age: 65,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
  {
    id: 11,
    name: "Chidinma Afolabi",
    status: "inactive",
    gender: "female",
    NHR_ID: "485 777 3456",
    age: 32,
    address: "39, Aromire close, Iseyin, Ogun state.",
  },
];
